/*!CK:3203375977!*//*1415709940,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["3dz44"]); }

__d("ActorURIConfig",[],function(a,b,c,d,e,f){e.exports={PARAMETER_ACTOR:"av"};},null);
__d("MComposerDataStoreKeys",[],function(a,b,c,d,e,f){e.exports={COMPOSITION:"COMPOSITION",ON_CANCEL:"ON_CANCEL",ON_SUBMIT:"ON_SUBMIT"};},null);
__d("MComposerSigils",[],function(a,b,c,d,e,f){e.exports={ENTRY_TRIGGER_LEGACY:"show_composer",ENTRY_TRIGGER:"composer_entry_trigger"};},null);
__d("MComposerTypes",[],function(a,b,c,d,e,f){e.exports={ACTIVITY:"activity",CHECKIN:"checkin",EDIT:"edit",GROUP_SELL:"group_sell",PHOTO:"photo",RECOMMENDATION:"recommendation",SHARE:"share",STATUS:"status"};},null);
__d("MComposerWaterfallEvent",[],function(a,b,c,d,e,f){e.exports={COMPOSER_CANCEL:"composer_cancel",COMPOSER_CANCEL_INTENT:"intent_composer_cancel",COMPOSER_ENTRY:"composer_entry",COMPOSER_NOT_RENDERED:"composer_not_renderer",COMPOSER_POST:"composer_post",COMPOSER_POST_CANCEL:"composer_post_cancel",COMPOSER_POST_FAILURE:"composer_post_failure",COMPOSER_POST_FAILURE_FATAL:"composer_post_fatal_failure",COMPOSER_POST_FAILURE_GIVEUP:"composer_post_giveup_failure",COMPOSER_POST_SUCCESS:"composer_post_success",COMPOSER_WRITTEN:"composer_written",ALBUM_ADD:"add_album",ALBUM_CANCEL:"cancel_album",ALBUM_INTENT:"intent_album",ALBUM_REMOVE:"remove_album",FRIEND_TAG_ADD:"add_friend_tag",FRIEND_TAG_CANCEL:"cancel_friend_tag",FRIEND_TAG_INTENT:"intent_friend_tag",FRIEND_TAG_REMOVE:"remove_friend_tag",FRIEND_TAG_SEARCH:"search_friend_tag",FRIEND_SHOW_MORE:"show_more_friend_tag",LOCATION_ADD:"add_location",LOCATION_CANCEL:"cancel_location",LOCATION_INTENT:"intent_location",LOCATION_REMOVE:"remove_location",LOCATION_SCROLL:"scroll_location",LOCATION_SEARCH:"search_location",MINUTIAE_ADD:"add_minutiae",MINUTIAE_CANCEL:"cancel_minutiae",MINUTIAE_CHANGE_ICON:"change_icon_minutiae",MINUTIAE_CHANGE_ICON_CANCEL:"change_icon_cancel_minutiae",MINUTIAE_CHANGE_ICON_INTENT:"change_icon_intent_minutiae",MINUTIAE_INTENT:"intent_minutiae",MINUTIAE_REMOVE:"remove_minutiae",MINUTIAE_SCROLL:"scroll_minutiae",MINUTIAE_SEARCH:"search_minutiae",MINUTIAE_TYPE_CLICK:"type_click_minutiae",MINUTIAE_SEE_MORE:"see_more_minutiae",MINUTIAE_CHAIN_SKIP:"skip_chain_minutiae",MINUTIAE_CHAIN_SUGGEST:"suggest_chain_minutiae",MINUTIAE_ICONPICKER_QUERY:"minutiae_iconpicker_query",MINUTIAE_ICONPICKER_BOOTSTRAP:"minutiae_iconpicker_bootstrap",MINUTIAE_ICONPICKER_SELECT:"minutiae_iconpicker_select",MEDIA_INTENT:"intent_media",MEDIA_CANCEL:"cancel_media",PHOTO_ADD:"add_photo",PHOTO_ADD_FAILURE:"add_photo_failure",PHOTO_ADD_SUCCESS:"add_photo_success",PHOTO_REMOVE:"remove_photo",PRIVACY_ADD:"add_privacy",PRIVACY_CANCEL:"cancel_privacy",PRIVACY_INTENT:"intent_privacy",PRIVACY_SCROLL:"scroll_privacy",PRIVACY_SEE_ALL_LISTS:"see_all_lists_privacy",SELECT_FRIEND_TIMELINE_INTENT:"intent_select_friend_timeline",SELECT_FRIEND_TIMELINE_ADD:"add_select_friend_timeline",SELECT_FRIEND_TIMELINE_CANCEL:"cancel_select_friend_timeline",SERVER_POST_BEGIN:"server_composer_post_begin",SERVER_POST_FAILURE:"server_composer_post_failure",SERVER_POST_SUCCESS:"server_composer_post_succeeded",POST_POST_WITH_TAG_BEGIN:"post_post_with_tag_begin",POST_POST_WITH_TAG_FAILURE:"post_post_with_tag_failure",POST_POST_WITH_TAG_SUCCESS:"post_post_with_tag_success",TARGET_SELECTOR_INTENT:"intent_target_selector",TARGET_SELECTOR_CANCEL:"cancel_target_selector",VIDEO_ADD:"add_video",VIDEO_ADD_FAILURE:"add_video_failure",VIDEO_ADD_SUCCESS:"add_video_success",VIDEO_REMOVE:"remove_video"};},null);
__d("MCompositionConfigFields",[],function(a,b,c,d,e,f){e.exports={OPENED_AT:"opened_at",SESSION_ID:"csid",ACTION:"action",COMPOSER_TITLE:"composertitle",COMPOSER_TYPE:"composer_type",INPUT_NAME:"inputname",PLACEHOLDER:"placeholder",BUTTON_TEXT_SUBMIT:"button_text_submit",TARGET_ID:"targetid",CANCEL_CONFIRMATION_MESSAGE:"cancel_confirm_message",DISABLE_MENTIONS:"disable_mentions",DISABLE_OG_TAG:"disable_og_tags",DISABLE_PEOPLE_TAGS:"disable_people_tags",DISABLE_PHOTOS:"disable_photos",DISABLE_ALBUM:"disable_album",DISABLE_PLACE_TAG:"disable_place_tag",DISABLE_PRIVACY:"disable_privacy",DISABLE_SUBMIT_REQUEST:"disable_submit_request",FORCE_ASYNC:"forceasync",SYNC_SUBMIT:"syncsubmit",PIN_PLACE:"pinplace",PIN_PRIVACY:"pinprivacy",SHOW_POST_TYPE_SELECTOR:"showposttypeselector",CONTEXTUAL_MESSAGE:"contextualmessage",SKIP_FOCUS:"skip_focus"};},null);
__d("MCompositionShareFields",[],function(a,b,c,d,e,f){e.exports={ID:"ID",FEEDBACK_SOURCE:"FEEDBACK_SOURCE",DISABLED_LINKS:"DISABLED_LINKS",SHARE_URI:"SHARE_URI"};},null);
__d("MCompositionStoreID",[],function(a,b,c,d,e,f){e.exports={CONFIG:"CONFIG",GROUP_SELL:"GROUP_SELL",MINUTIAE:"MINUTIAE",PHOTO:"PHOTO",PLACE:"PLACE",SHARE:"SHARE",STATUS:"STATUS",WITH_TAGS:"WITH_TAGS",PRIVACY:"PRIVACY"};},null);
__d("MPageletTypes",[],function(a,b,c,d,e,f){e.exports={CHROME:"chrome",CONTENT:"content"};},null);
__d("PlatformVersions",[],function(a,b,c,d,e,f){e.exports={LATEST:"v2.3",versions:{UNVERSIONED:"unversioned",V1_0:"v1.0",V2_0:"v2.0",V2_1:"v2.1",V2_2:"v2.2",V2_3:"v2.3"}};},null);
__d("PUWApplications",[],function(a,b,c,d,e,f){e.exports={WEB_SIMPLE:"web_simple",WEB_FLASH:"web_flash",WEB_HTML5:"web_html5",WEB_COMPOSER:"web_composer",WEB_ARCHIVE:"web_archive",WEB_MESSENGER:"web_messenger",WEB_OMNIPICKER:"web_omnipicker",WEB_MUSE_OMNIPICKER:"web_muse_omnipicker",WEB_SAY_THANKS:"web_say_thanks",WEB_GOODWILL_CAMPAIGN_OMNIPICKER:"web_goodwill_campaign_omnipicker",WEB_M_ZERO:"web_m_zero",WEB_M_BASIC:"web_m_basic",WEB_M_TOUCH:"web_m_touch",MOBILE_FB4IOS:"mobile_fb4ios",MOBILE_FB4IOS_SNAP:"mobile_fb4ios_snap",MOBILE_FB4A:"mobile_fb4a",MOBILE_PMA_ANDROID:"mobile_pma_android",MOBILE_PMA_IOS:"mobile_pma_ios",THIRD_PARTY:"third_party"};},null);
__d("PUWErrorCodes",[],function(a,b,c,d,e,f){e.exports={BAD_JPEG:9901,WORKER_TERMINATED:9902,UNKNOWN_RESIZE_ERROR:9903,WORKER_ABORT:9904};},null);
__d("PUWSteps",[],function(a,b,c,d,e,f){e.exports={CLIENT_FLOW_BEGIN:"client_flow_begin",CLIENT_SELECT_BEGIN:"client_select_begin",CLIENT_SELECT_SUCCESS:"client_select_success",CLIENT_SELECT_CANCEL:"client_select_cancel",CLIENT_SELECT_FAIL:"client_select_fail",CLIENT_FLOW_POST:"client_flow_post",CLIENT_TRANSFER_BATCH_BEGIN:"client_transfer_batch_begin",CLIENT_UPLOAD_BEGIN:"client_upload_begin",CLIENT_PROCESS_BEGIN:"client_process_begin",CLIENT_PROCESS_SUCCESS:"client_process_success",CLIENT_PROCESS_CANCEL:"client_process_cancel",CLIENT_PROCESS_SKIP:"client_process_skip",CLIENT_PROCESS_FAIL:"client_process_fail",CLIENT_PROCESS_UNAVAILABLE:"client_process_unavailable",CLIENT_TRANSFER_ENQUEUE:"client_transfer_enqueue",CLIENT_TRANSFER_BEGIN:"client_transfer_begin",CLIENT_TRANSFER_SUCCESS:"client_transfer_success",CLIENT_TRANSFER_CANCEL:"client_transfer_cancel",CLIENT_TRANSFER_FAIL:"client_transfer_fail",CLIENT_TRANSFER_MANUAL_RETRY:"client_transfer_manual_retry",CLIENT_UPLOAD_SUCCESS:"client_upload_success",CLIENT_UPLOAD_FAIL:"client_upload_fail",CLIENT_UPLOAD_CANCEL:"client_upload_cancel",CLIENT_UPLOAD_REMOVE:"client_upload_remove",CLIENT_FACEREC_BEGIN:"client_facerec_begin",CLIENT_FACEREC_SUCCESS:"client_facerec_success",CLIENT_FACEREC_FAIL:"client_facerec_fail",CLIENT_PHOTO_PREVIEW_OPEN:"client_photo_preview_open",CLIENT_PHOTO_PREVIEW_CLOSE:"client_photo_preview_close",CLIENT_TRANSFER_BATCH_SUCCESS:"client_transfer_batch_success",CLIENT_TRANSFER_BATCH_CANCEL:"client_transfer_batch_cancel",CLIENT_TRANSFER_BATCH_FAIL:"client_transfer_batch_fail",CLIENT_PUBLISH_ENQUEUE:"client_publish_enqueue",CLIENT_PUBLISH_BEGIN:"client_publish_begin",CLIENT_PUBLISH_SUCCESS:"client_publish_success",CLIENT_PUBLISH_FAIL:"client_publish_fail",CLIENT_ATTEMPT_FAIL:"client_attempt_fail",CLIENT_FLOW_SUCCESS:"client_flow_success",CLIENT_FLOW_FATAL:"client_flow_fatal",CLIENT_FLOW_GIVEUP:"client_flow_giveup",CLIENT_FLOW_CANCEL:"client_flow_cancel",CLIENT_FLOW_FAIL:"client_flow_fail",CLIENT_FLOW_INCOMPLETE:"client_flow_incomplete",CLIENT_ATTEMPT_INCOMPLETE:"client_attempt_incomplete",CLIENT_FLOW_RETRY:"client_flow_retry",CLIENT_ATTEMPT_RETRY:"client_attempt_retry",CLIENT_DIAGNOSTIC:"client_diagnostic",CLIENT_QUALITY_SWITCH:"client_quality_switch",CLIENT_CANCEL_SURVEY:"client_cancel_survey",SERVER_UPLOAD_BEGIN:"server_upload_begin",SERVER_UPLOAD_SUCCESS:"server_upload_success",SERVER_UPLOAD_FAIL:"server_upload_fail",SERVER_PUBLISH_BEGIN:"server_publish_begin",SERVER_PUBLISH_SUCCESS:"server_publish_success",SERVER_PUBLISH_FAIL:"server_publish_fail",SERVER_RECEIVER_BEGIN:"server_receiver_begin",SERVER_RECEIVER_PUBLISH_BEGIN:"server_receiver_publish_begin",SERVER_SENTRY_RESTRICTION:"server_sentry_restriction"};},null);
__d("XAdsPreferencesAdInfoControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/ads\/preferences\/",{ad_id:{type:"Int"},tracking:{type:"String"},optout_url:{type:"String"},rtb_partner_id:{type:"Int"},show_ad_choices:{type:"Bool"},__asyncDialog:{type:"Int"}});},null);
__d("XAdsPreferencesFeedbackControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/ads\/preferences\/feeedback\/",{ad_id:{type:"Int",required:true},favorite:{type:"Enum",required:true}});},null);
__d("XChatBuddyCountControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/chat\/online_friend_count\/",{});},null);
__d("XComposerAsyncLoaderControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/composer\/async_loader\/",{});},null);
__d("XFeedNewStoriesBadgeControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/feed\/badge\/",{});},null);
__d("XMessagingDeferredAttachmentControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/messages\/load_deferred_attachment\/",{dest_id:{type:"String",required:true},mid:{type:"String",required:true}});},null);
__d("XMessagingMarkReadControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/messaging\/mark_read\/",{});},null);
__d("XMobilePhotosSaveUnpublishedControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/_mupload_\/photo\/x\/saveunpublished\/",{thumbnail_width:{type:"Int"},thumbnail_height:{type:"Int"},waterfall_app_name:{type:"String"},waterfall_id:{type:"String"},waterfall_source:{type:"String"},filter_type:{type:"Int"},upload_id:{type:"String"},target_id:{type:"Int"},csid:{type:"String"},js_request_module_name:{type:"String"}});},null);
__d("XMobileSearchTrendingLoggingControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/graphsearch\/trending\/logging\/",{topic_ids:{type:"IntVector",required:true},source:{type:"String",required:true},positions:{type:"IntVector",required:true},query_id:{type:"Int",required:true},event:{type:"String",required:true}});},null);
__d("XStickerPackImagesControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/stickers\/{pack_id}\/images\/",{pack_id:{type:"Int",required:true},sticker_size:{type:"Int"}});},null);
__d("XStickerStorePermalinkControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/stickers\/",{tab:{type:"String"},redirect_uri:{type:"String"},is_messenger:{type:"Bool"}});},null);
__d("XTimelineCoverSwapControllerURIBuilder",["XControllerURIBuilder"],function(a,b,c,d,e,f){e.exports=b("XControllerURIBuilder").create("\/timeline\/cover\/swap\/",{profile_id:{type:"Int",required:true},full_bleed_profile_pic:{type:"Bool"}});},null);