/*!CK:213882927!*//*1415121191,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["hOhuu"]); }

__d("TooltipLink",["Parent","Tooltip"],function(a,b,c,d,e,f,g,h){var i={setTooltipText:function(j,k){j=g.byTag(j,'a');j&&h.set(j,k);}};e.exports=i;},null);
__d("DynamicFacepile",["DOM","TooltipLink","URI","XHPTemplate","copyProperties"],function(a,b,c,d,e,f,g,h,i,j,k){function l(){}k(l.prototype,{init:function(m,n,o,p){this._facepile=o;this._maxFacepileSize=n;this._memberIDs=m;this._facepileItemMap={};var q=g.scry(this._facepile,'li');for(var r=0,s=m.length;r<s;++r)this._facepileItemMap[m[r]]=q[r];this._template=p;},containsID:function(m){return this._facepileItemMap[m];},removeFacepileItem:function(m){var n=this._facepileItemMap[m.uid];if(!n)return;delete this._facepileItemMap[m.uid];this._memberIDs.splice(this._memberIDs.indexOf(m.uid),1);g.remove(n);},addFacepileItem:function(m){var n=this._template.render(),o=j.getNode(n,'img');o.src=m.photo;var p=j.getNode(n,'anchor');p.href=i('/profile.php').addQueryData({id:m.uid});h.setTooltipText(p,m.name);g.prependContent(this._facepile,n);this._facepileItemMap[m.uid]=n;this._memberIDs.unshift(m.uid);if(this._memberIDs.length>this._maxFacepileSize){var q=this._memberIDs.pop(),r=this._facepileItemMap[q];g.remove(r);delete this._facepileItemMap[q];}}});e.exports=l;},null);
__d("FriendsDashSideCol",["Arbiter","AsyncRequest","CSS","DOM","PageTransitions","$"],function(a,b,c,d,e,f,g,h,i,j,k,l){var m={init:function(n){this._flid=n;var o='listeditor/friend_lists_changed',p=g.subscribe(o,function(q,r){if(q==o&&r.list_info.list_id==this._flid){if(r.refresh_member_box)new h('/ajax/friends/lists/list_modified.php').setMethod('GET').setReadOnly(true).setData({list_id:this._flid}).send();if(r.removed_uid){j.scry(l('home_stream'),'.aid_'+r.removed_uid).forEach(i.hide);}else if(r.undo_remove&&r.added_uid)j.scry(l('home_stream'),'.aid_'+r.added_uid).forEach(i.show);}}.bind(this),g.SUBSCRIBE_NEW);k.registerHandler(g.unsubscribe.bind(null,p));}};e.exports=m;},null);
__d("legacy:friends-dash-sidecol-js",["FriendsDashSideCol"],function(a,b,c,d){a.FriendsDashSideCol=b('FriendsDashSideCol');},3);
__d("FriendListFilterNUXDialog",["Arbiter"],function(a,b,c,d,e,f,g){var h={init:function(i){g.subscribe(['FriendListMemberTypeahead/add','FriendListSuggestions/add'],function(){i.hide();});}};e.exports=h;},null);
__d("FriendListMembersBox",["Arbiter","CSS","DOM","DynamicFacepile","PageTransitions","copyProperties","tx"],function(a,b,c,d,e,f,g,h,i,j,k,l,m){function n(){}l(n.prototype,{init:function(o,p,q,r,s,t,u){this._root=o;this._flid=p;this._listSize=r;this._headerTitle=i.find(this._root,'.uiHeaderTitle');this._headerActions=i.find(this._root,'.uiHeaderActions a');this._facepile=new j();this._facepile.init(q,s,t.firstChild,u);var v=[g.subscribe(['FriendListSuggestions/add','FriendListMemberTypeahead/add','FriendListHovercard/add'],this.handleAddEvent.bind(this)),g.subscribe('FriendListHovercard/remove',this.handleRemoveEvent.bind(this))];k.registerHandler(function(){v.forEach(g.unsubscribe);});},handleAddEvent:function(o,p){if(p.flid!==this._flid||!p.uid)return;if(this._facepile.containsID(p.uid))return;if(!p.photo||!p.name){d(['ShortProfiles'],function(q){q.get(p.uid,function(r,s){if(s.exist){r.flid=this._flid;r.photo=s.thumbSrc;r.name=s.firstName;this._facepile.addFacepileItem(r);}}.bind(this,p));}.bind(this));}else this._facepile.addFacepileItem(p);h.removeClass(this._root,'empty');h.show(this._headerActions);this._listSize++;this.updateListSize();},handleRemoveEvent:function(o,p){if(p.flid!==this._flid||!p.uid)return;this._listSize--;this.updateListSize();this._facepile.removeFacepileItem(p);},updateListSize:function(){i.setContent(this._headerTitle,m._("\u5217\u8868\u4e2d\uff08{num_members}\uff09",{num_members:this._listSize}));}});e.exports=n;},null);
__d("legacy:FriendListMembersBox",["FriendListMembersBox"],function(a,b,c,d){a.FriendListMembersBox=b('FriendListMembersBox');},3);
__d("FriendListSuggestions",["Event","Arbiter","AsyncRequest","AsyncSignal","CSS","DOM","DynamicFriendListEducation","PageTransitions","Parent","copyProperties","csx","ge","getElementText"],function(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s){function t(){}p(t.prototype,{init:function(u,v,w,x,y){this._container=u;this._flid=v;this._shouldSave=w;this._context=x;this._source=y;var z=g.listen(u,'click',function(ba){var ca=ba.getTarget();o.byClass(ca,'addLink')&&this._handleAdd(ca);o.byClass(ca,'declineButton')&&this._handleDecline(ca);}.bind(this)),aa=h.subscribe('FriendListMemberTypeahead/add',function(ba,ca){var da=r('suggestion_'+ca.uid);da&&this._swap(da);}.bind(this));n.registerHandler(function(){z.remove();aa.unsubscribe();this._explicitHover&&this._explicitHover.uninstall();}.bind(this));},_handleDecline:function(u){var v=o.byTag(u,'li');this._swap(v);},_handleAdd:function(u){var v=o.byTag(u,'li'),w=this._getUIDFromItem(v),x=function(y){if(y&&y.nux_cancel)return;this._swap(v);if(this._shouldSave)this._save(w,y);var z=l.scry(v,"img._s0")[0],aa=l.find(v,'.userSuggestionName');h.inform('FriendListSuggestions/add',{flid:this._flid,uid:w,name:s(aa),photo:z.src});}.bind(this);m.showContextualDialog(this._flid,w,u,x);},_getUIDFromItem:function(u){return ''+u.id.split('_')[1];},_swap:function(u){l.remove(u);var v=l.scry(this._container,'li.hidden_elem')[0];if(!v)return;k.show(v);var w=this._getUIDFromItem(v),x=''+v.getAttribute('data-coeff-key'),y={tids:[w],key:x};new j('/friends/ajax/log_data.php',y).send();},_save:function(u,v){var w={flid:this._flid,id:u,add:1,source:this._source};w[this.context]=1;if(v)p(w,v);new i().setURI('/friends/ajax/lists.php').setData(w).send();}});e.exports=t;},null);
__d("legacy:FriendListSuggestions",["FriendListSuggestions"],function(a,b,c,d){a.FriendListSuggestions=b('FriendListSuggestions');},3);
__d("FriendListMemberBoxTypeahead",["Arbiter","AsyncRequest","CSS","DynamicFriendListEducation","Event","PageTransitions","Style","copyProperties","removeFromArray"],function(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o){function p(){}n(p.prototype,{init:function(q,r,s){k.listen(q.getCore().getElement(),'keyup',function(event){i.conditionClass(event.getTarget(),'noPadding',m.get(event.getTarget(),'direction')=='rtl');});q.subscribe('select',function(u,v){var w=function(y){g.inform('FriendListMemberTypeahead/add',{flid:r,uid:v.selected.uid,name:v.selected.text,path:v.selected.path,photo:v.selected.photo});var z={add:1,search:1,source:s,flid:r,id:v.selected.uid};n(z,y);new h().setURI('/friends/ajax/lists.php').setData(z).send();};if(v.selected.subscribee||v.selected.type=='page')return w();j.showDialog(r,v.selected.uid,w);var x=q.getData().getExclusions();x.push(v.selected.uid);q.getData().setExclusions(x);});var t=g.subscribe('listeditor/friend_lists_changed',function(u,v){if(v.list_info.list_id==r){var w=q.getData().getExclusions();if(v.removed_uid){o(w,v.removed_uid);}else if(v.added_uid)w.push(v.added_uid);q.getData().setExclusions(w);}},g.SUBSCRIBE_NEW);l.registerHandler(g.unsubscribe.bind(null,t));}});e.exports=p;},null);
__d("legacy:FriendListMemberBoxTypeahead",["FriendListMemberBoxTypeahead"],function(a,b,c,d){a.FriendListMemberBoxTypeahead=b('FriendListMemberBoxTypeahead');},3);